// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: optical/optical.proto

package optical

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpticalService_RecomputePaths_FullMethodName = "/optical.OpticalService/RecomputePaths"
	OpticalService_GetPath_FullMethodName        = "/optical.OpticalService/GetPath"
	OpticalService_Health_FullMethodName         = "/optical.OpticalService/Health"
)

// OpticalServiceClient is the client API for OpticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OpticalService handles optical path computation and signal budget calculations
type OpticalServiceClient interface {
	// Recompute optical paths for affected ONTs after topology changes
	// This is the critical performance bottleneck (currently O(N²) in Python)
	RecomputePaths(ctx context.Context, in *RecomputeRequest, opts ...grpc.CallOption) (*RecomputeResponse, error)
	// Get optical path details for a single ONT (debugging/UI)
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*OpticalPath, error)
	// Health check endpoint
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type opticalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpticalServiceClient(cc grpc.ClientConnInterface) OpticalServiceClient {
	return &opticalServiceClient{cc}
}

func (c *opticalServiceClient) RecomputePaths(ctx context.Context, in *RecomputeRequest, opts ...grpc.CallOption) (*RecomputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecomputeResponse)
	err := c.cc.Invoke(ctx, OpticalService_RecomputePaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opticalServiceClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*OpticalPath, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpticalPath)
	err := c.cc.Invoke(ctx, OpticalService_GetPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opticalServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, OpticalService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpticalServiceServer is the server API for OpticalService service.
// All implementations must embed UnimplementedOpticalServiceServer
// for forward compatibility.
//
// OpticalService handles optical path computation and signal budget calculations
type OpticalServiceServer interface {
	// Recompute optical paths for affected ONTs after topology changes
	// This is the critical performance bottleneck (currently O(N²) in Python)
	RecomputePaths(context.Context, *RecomputeRequest) (*RecomputeResponse, error)
	// Get optical path details for a single ONT (debugging/UI)
	GetPath(context.Context, *GetPathRequest) (*OpticalPath, error)
	// Health check endpoint
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedOpticalServiceServer()
}

// UnimplementedOpticalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpticalServiceServer struct{}

func (UnimplementedOpticalServiceServer) RecomputePaths(context.Context, *RecomputeRequest) (*RecomputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecomputePaths not implemented")
}
func (UnimplementedOpticalServiceServer) GetPath(context.Context, *GetPathRequest) (*OpticalPath, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedOpticalServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedOpticalServiceServer) mustEmbedUnimplementedOpticalServiceServer() {}
func (UnimplementedOpticalServiceServer) testEmbeddedByValue()                        {}

// UnsafeOpticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpticalServiceServer will
// result in compilation errors.
type UnsafeOpticalServiceServer interface {
	mustEmbedUnimplementedOpticalServiceServer()
}

func RegisterOpticalServiceServer(s grpc.ServiceRegistrar, srv OpticalServiceServer) {
	// If the following call pancis, it indicates UnimplementedOpticalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpticalService_ServiceDesc, srv)
}

func _OpticalService_RecomputePaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecomputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpticalServiceServer).RecomputePaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpticalService_RecomputePaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpticalServiceServer).RecomputePaths(ctx, req.(*RecomputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpticalService_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpticalServiceServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpticalService_GetPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpticalServiceServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpticalService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpticalServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpticalService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpticalServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpticalService_ServiceDesc is the grpc.ServiceDesc for OpticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "optical.OpticalService",
	HandlerType: (*OpticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecomputePaths",
			Handler:    _OpticalService_RecomputePaths_Handler,
		},
		{
			MethodName: "GetPath",
			Handler:    _OpticalService_GetPath_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _OpticalService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optical/optical.proto",
}
