// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: port_summary.proto

package port_summary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortSummaryService_GetPortSummary_FullMethodName     = "/port_summary.PortSummaryService/GetPortSummary"
	PortSummaryService_GetBulkPortSummary_FullMethodName = "/port_summary.PortSummaryService/GetBulkPortSummary"
	PortSummaryService_InvalidateCache_FullMethodName    = "/port_summary.PortSummaryService/InvalidateCache"
	PortSummaryService_HealthCheck_FullMethodName        = "/port_summary.PortSummaryService/HealthCheck"
)

// PortSummaryServiceClient is the client API for PortSummaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Port Summary Service - Fast interface summary for devices
// Replaces slow Python bulk queries with in-memory Go service
type PortSummaryServiceClient interface {
	// Get port summary for a single device
	GetPortSummary(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*PortSummaryResponse, error)
	// Get port summaries for multiple devices (bulk)
	GetBulkPortSummary(ctx context.Context, in *BulkDeviceRequest, opts ...grpc.CallOption) (*BulkPortSummaryResponse, error)
	// Invalidate cache for a device (triggered by events)
	InvalidateCache(ctx context.Context, in *InvalidateCacheRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Health check endpoint
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type portSummaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortSummaryServiceClient(cc grpc.ClientConnInterface) PortSummaryServiceClient {
	return &portSummaryServiceClient{cc}
}

func (c *portSummaryServiceClient) GetPortSummary(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*PortSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortSummaryResponse)
	err := c.cc.Invoke(ctx, PortSummaryService_GetPortSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portSummaryServiceClient) GetBulkPortSummary(ctx context.Context, in *BulkDeviceRequest, opts ...grpc.CallOption) (*BulkPortSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkPortSummaryResponse)
	err := c.cc.Invoke(ctx, PortSummaryService_GetBulkPortSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portSummaryServiceClient) InvalidateCache(ctx context.Context, in *InvalidateCacheRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PortSummaryService_InvalidateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portSummaryServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PortSummaryService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortSummaryServiceServer is the server API for PortSummaryService service.
// All implementations must embed UnimplementedPortSummaryServiceServer
// for forward compatibility.
//
// Port Summary Service - Fast interface summary for devices
// Replaces slow Python bulk queries with in-memory Go service
type PortSummaryServiceServer interface {
	// Get port summary for a single device
	GetPortSummary(context.Context, *DeviceRequest) (*PortSummaryResponse, error)
	// Get port summaries for multiple devices (bulk)
	GetBulkPortSummary(context.Context, *BulkDeviceRequest) (*BulkPortSummaryResponse, error)
	// Invalidate cache for a device (triggered by events)
	InvalidateCache(context.Context, *InvalidateCacheRequest) (*emptypb.Empty, error)
	// Health check endpoint
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPortSummaryServiceServer()
}

// UnimplementedPortSummaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortSummaryServiceServer struct{}

func (UnimplementedPortSummaryServiceServer) GetPortSummary(context.Context, *DeviceRequest) (*PortSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortSummary not implemented")
}
func (UnimplementedPortSummaryServiceServer) GetBulkPortSummary(context.Context, *BulkDeviceRequest) (*BulkPortSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBulkPortSummary not implemented")
}
func (UnimplementedPortSummaryServiceServer) InvalidateCache(context.Context, *InvalidateCacheRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateCache not implemented")
}
func (UnimplementedPortSummaryServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPortSummaryServiceServer) mustEmbedUnimplementedPortSummaryServiceServer() {}
func (UnimplementedPortSummaryServiceServer) testEmbeddedByValue()                            {}

// UnsafePortSummaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortSummaryServiceServer will
// result in compilation errors.
type UnsafePortSummaryServiceServer interface {
	mustEmbedUnimplementedPortSummaryServiceServer()
}

func RegisterPortSummaryServiceServer(s grpc.ServiceRegistrar, srv PortSummaryServiceServer) {
	// If the following call pancis, it indicates UnimplementedPortSummaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortSummaryService_ServiceDesc, srv)
}

func _PortSummaryService_GetPortSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortSummaryServiceServer).GetPortSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortSummaryService_GetPortSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortSummaryServiceServer).GetPortSummary(ctx, req.(*DeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortSummaryService_GetBulkPortSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortSummaryServiceServer).GetBulkPortSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortSummaryService_GetBulkPortSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortSummaryServiceServer).GetBulkPortSummary(ctx, req.(*BulkDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortSummaryService_InvalidateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortSummaryServiceServer).InvalidateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortSummaryService_InvalidateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortSummaryServiceServer).InvalidateCache(ctx, req.(*InvalidateCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortSummaryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortSummaryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortSummaryService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortSummaryServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PortSummaryService_ServiceDesc is the grpc.ServiceDesc for PortSummaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortSummaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "port_summary.PortSummaryService",
	HandlerType: (*PortSummaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortSummary",
			Handler:    _PortSummaryService_GetPortSummary_Handler,
		},
		{
			MethodName: "GetBulkPortSummary",
			Handler:    _PortSummaryService_GetBulkPortSummary_Handler,
		},
		{
			MethodName: "InvalidateCache",
			Handler:    _PortSummaryService_InvalidateCache_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PortSummaryService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "port_summary.proto",
}
