// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: port_summary.proto

package port_summary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for single device
type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_port_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// Request for multiple devices (bulk)
type BulkDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []string               `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDeviceRequest) Reset() {
	*x = BulkDeviceRequest{}
	mi := &file_port_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeviceRequest) ProtoMessage() {}

func (x *BulkDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeviceRequest.ProtoReflect.Descriptor instead.
func (*BulkDeviceRequest) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{1}
}

func (x *BulkDeviceRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

// Interface summary information
type InterfaceSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PortRole        string                 `protobuf:"bytes,3,opt,name=port_role,json=portRole,proto3" json:"port_role,omitempty"`                      // PON, ACCESS, UPLINK, etc.
	EffectiveStatus string                 `protobuf:"bytes,4,opt,name=effective_status,json=effectiveStatus,proto3" json:"effective_status,omitempty"` // UP, DOWN, DEGRADED
	Occupancy       int32                  `protobuf:"varint,5,opt,name=occupancy,proto3" json:"occupancy,omitempty"`                                   // Number of connected devices
	Capacity        *int32                 `protobuf:"varint,6,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`                               // Max capacity (null for unlimited)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterfaceSummary) Reset() {
	*x = InterfaceSummary{}
	mi := &file_port_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceSummary) ProtoMessage() {}

func (x *InterfaceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceSummary.ProtoReflect.Descriptor instead.
func (*InterfaceSummary) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterfaceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceSummary) GetPortRole() string {
	if x != nil {
		return x.PortRole
	}
	return ""
}

func (x *InterfaceSummary) GetEffectiveStatus() string {
	if x != nil {
		return x.EffectiveStatus
	}
	return ""
}

func (x *InterfaceSummary) GetOccupancy() int32 {
	if x != nil {
		return x.Occupancy
	}
	return 0
}

func (x *InterfaceSummary) GetCapacity() int32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

// Response for single device
type PortSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceSummary    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSummaryResponse) Reset() {
	*x = PortSummaryResponse{}
	mi := &file_port_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSummaryResponse) ProtoMessage() {}

func (x *PortSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSummaryResponse.ProtoReflect.Descriptor instead.
func (*PortSummaryResponse) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{3}
}

func (x *PortSummaryResponse) GetInterfaces() []*InterfaceSummary {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// Response for multiple devices (bulk)
type BulkPortSummaryResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Summaries     map[string]*PortSummaryResponse `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkPortSummaryResponse) Reset() {
	*x = BulkPortSummaryResponse{}
	mi := &file_port_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPortSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPortSummaryResponse) ProtoMessage() {}

func (x *BulkPortSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPortSummaryResponse.ProtoReflect.Descriptor instead.
func (*BulkPortSummaryResponse) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{4}
}

func (x *BulkPortSummaryResponse) GetSummaries() map[string]*PortSummaryResponse {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// Request to invalidate cache
type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_port_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateCacheRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// Health check response
type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CachedDevices    int32                  `protobuf:"varint,2,opt,name=cached_devices,json=cachedDevices,proto3" json:"cached_devices,omitempty"`
	CachedInterfaces int32                  `protobuf:"varint,3,opt,name=cached_interfaces,json=cachedInterfaces,proto3" json:"cached_interfaces,omitempty"`
	CachedLinks      int32                  `protobuf:"varint,4,opt,name=cached_links,json=cachedLinks,proto3" json:"cached_links,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_port_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_port_summary_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetCachedDevices() int32 {
	if x != nil {
		return x.CachedDevices
	}
	return 0
}

func (x *HealthCheckResponse) GetCachedInterfaces() int32 {
	if x != nil {
		return x.CachedInterfaces
	}
	return 0
}

func (x *HealthCheckResponse) GetCachedLinks() int32 {
	if x != nil {
		return x.CachedLinks
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_port_summary_proto protoreflect.FileDescriptor

const file_port_summary_proto_rawDesc = "" +
	"\n" +
	"\x12port_summary.proto\x12\fport_summary\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\rDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"2\n" +
	"\x11BulkDeviceRequest\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\"\xca\x01\n" +
	"\x10InterfaceSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tport_role\x18\x03 \x01(\tR\bportRole\x12)\n" +
	"\x10effective_status\x18\x04 \x01(\tR\x0feffectiveStatus\x12\x1c\n" +
	"\toccupancy\x18\x05 \x01(\x05R\toccupancy\x12\x1f\n" +
	"\bcapacity\x18\x06 \x01(\x05H\x00R\bcapacity\x88\x01\x01B\v\n" +
	"\t_capacity\"U\n" +
	"\x13PortSummaryResponse\x12>\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x1e.port_summary.InterfaceSummaryR\n" +
	"interfaces\"\xce\x01\n" +
	"\x17BulkPortSummaryResponse\x12R\n" +
	"\tsummaries\x18\x01 \x03(\v24.port_summary.BulkPortSummaryResponse.SummariesEntryR\tsummaries\x1a_\n" +
	"\x0eSummariesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.port_summary.PortSummaryResponseR\x05value:\x028\x01\"5\n" +
	"\x16InvalidateCacheRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xc0\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0ecached_devices\x18\x02 \x01(\x05R\rcachedDevices\x12+\n" +
	"\x11cached_interfaces\x18\x03 \x01(\x05R\x10cachedInterfaces\x12!\n" +
	"\fcached_links\x18\x04 \x01(\x05R\vcachedLinks\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion2\xdf\x02\n" +
	"\x12PortSummaryService\x12P\n" +
	"\x0eGetPortSummary\x12\x1b.port_summary.DeviceRequest\x1a!.port_summary.PortSummaryResponse\x12\\\n" +
	"\x12GetBulkPortSummary\x12\x1f.port_summary.BulkDeviceRequest\x1a%.port_summary.BulkPortSummaryResponse\x12O\n" +
	"\x0fInvalidateCache\x12$.port_summary.InvalidateCacheRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a!.port_summary.HealthCheckResponseB/Z-github.com/yourusername/unoc/gen/port_summaryb\x06proto3"

var (
	file_port_summary_proto_rawDescOnce sync.Once
	file_port_summary_proto_rawDescData []byte
)

func file_port_summary_proto_rawDescGZIP() []byte {
	file_port_summary_proto_rawDescOnce.Do(func() {
		file_port_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_port_summary_proto_rawDesc), len(file_port_summary_proto_rawDesc)))
	})
	return file_port_summary_proto_rawDescData
}

var file_port_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_port_summary_proto_goTypes = []any{
	(*DeviceRequest)(nil),           // 0: port_summary.DeviceRequest
	(*BulkDeviceRequest)(nil),       // 1: port_summary.BulkDeviceRequest
	(*InterfaceSummary)(nil),        // 2: port_summary.InterfaceSummary
	(*PortSummaryResponse)(nil),     // 3: port_summary.PortSummaryResponse
	(*BulkPortSummaryResponse)(nil), // 4: port_summary.BulkPortSummaryResponse
	(*InvalidateCacheRequest)(nil),  // 5: port_summary.InvalidateCacheRequest
	(*HealthCheckResponse)(nil),     // 6: port_summary.HealthCheckResponse
	nil,                             // 7: port_summary.BulkPortSummaryResponse.SummariesEntry
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_port_summary_proto_depIdxs = []int32{
	2, // 0: port_summary.PortSummaryResponse.interfaces:type_name -> port_summary.InterfaceSummary
	7, // 1: port_summary.BulkPortSummaryResponse.summaries:type_name -> port_summary.BulkPortSummaryResponse.SummariesEntry
	3, // 2: port_summary.BulkPortSummaryResponse.SummariesEntry.value:type_name -> port_summary.PortSummaryResponse
	0, // 3: port_summary.PortSummaryService.GetPortSummary:input_type -> port_summary.DeviceRequest
	1, // 4: port_summary.PortSummaryService.GetBulkPortSummary:input_type -> port_summary.BulkDeviceRequest
	5, // 5: port_summary.PortSummaryService.InvalidateCache:input_type -> port_summary.InvalidateCacheRequest
	8, // 6: port_summary.PortSummaryService.HealthCheck:input_type -> google.protobuf.Empty
	3, // 7: port_summary.PortSummaryService.GetPortSummary:output_type -> port_summary.PortSummaryResponse
	4, // 8: port_summary.PortSummaryService.GetBulkPortSummary:output_type -> port_summary.BulkPortSummaryResponse
	8, // 9: port_summary.PortSummaryService.InvalidateCache:output_type -> google.protobuf.Empty
	6, // 10: port_summary.PortSummaryService.HealthCheck:output_type -> port_summary.HealthCheckResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_port_summary_proto_init() }
func file_port_summary_proto_init() {
	if File_port_summary_proto != nil {
		return
	}
	file_port_summary_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_port_summary_proto_rawDesc), len(file_port_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_port_summary_proto_goTypes,
		DependencyIndexes: file_port_summary_proto_depIdxs,
		MessageInfos:      file_port_summary_proto_msgTypes,
	}.Build()
	File_port_summary_proto = out.File
	file_port_summary_proto_goTypes = nil
	file_port_summary_proto_depIdxs = nil
}
