# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import batch_pb2 as batch__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in batch_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BatchServiceStub:
    """BatchService handles bulk operations for links and devices
    All operations use single transactions for atomicity
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchCreateLinks = channel.unary_unary(
            "/batch.BatchService/BatchCreateLinks",
            request_serializer=batch__pb2.BatchCreateLinksRequest.SerializeToString,
            response_deserializer=batch__pb2.BatchCreateLinksResponse.FromString,
            _registered_method=True,
        )
        self.BatchDeleteLinks = channel.unary_unary(
            "/batch.BatchService/BatchDeleteLinks",
            request_serializer=batch__pb2.BatchDeleteLinksRequest.SerializeToString,
            response_deserializer=batch__pb2.BatchDeleteLinksResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/batch.BatchService/HealthCheck",
            request_serializer=batch__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=batch__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class BatchServiceServicer:
    """BatchService handles bulk operations for links and devices
    All operations use single transactions for atomicity
    """

    def BatchCreateLinks(self, request, context):
        """BatchCreateLinks creates multiple links in a single transaction
        Target: 64 links in <10s (vs 37 min Python sequential)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchDeleteLinks(self, request, context):
        """BatchDeleteLinks deletes multiple links in a single transaction
        Target: 64 links in <5s (vs 15-20 min Python sequential)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """HealthCheck verifies service is operational"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BatchCreateLinks": grpc.unary_unary_rpc_method_handler(
            servicer.BatchCreateLinks,
            request_deserializer=batch__pb2.BatchCreateLinksRequest.FromString,
            response_serializer=batch__pb2.BatchCreateLinksResponse.SerializeToString,
        ),
        "BatchDeleteLinks": grpc.unary_unary_rpc_method_handler(
            servicer.BatchDeleteLinks,
            request_deserializer=batch__pb2.BatchDeleteLinksRequest.FromString,
            response_serializer=batch__pb2.BatchDeleteLinksResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=batch__pb2.HealthCheckRequest.FromString,
            response_serializer=batch__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "batch.BatchService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("batch.BatchService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BatchService:
    """BatchService handles bulk operations for links and devices
    All operations use single transactions for atomicity
    """

    @staticmethod
    def BatchCreateLinks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/batch.BatchService/BatchCreateLinks",
            batch__pb2.BatchCreateLinksRequest.SerializeToString,
            batch__pb2.BatchCreateLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchDeleteLinks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/batch.BatchService/BatchDeleteLinks",
            batch__pb2.BatchDeleteLinksRequest.SerializeToString,
            batch__pb2.BatchDeleteLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/batch.BatchService/HealthCheck",
            batch__pb2.HealthCheckRequest.SerializeToString,
            batch__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
