# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from backend.proto import optical_pb2 as optical__pb2

GRPC_GENERATED_VERSION = "1.66.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in optical_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OpticalServiceStub:
    """OpticalService handles optical path computation and signal budget calculations"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecomputePaths = channel.unary_unary(
            "/optical.OpticalService/RecomputePaths",
            request_serializer=optical__pb2.RecomputeRequest.SerializeToString,
            response_deserializer=optical__pb2.RecomputeResponse.FromString,
            _registered_method=True,
        )
        self.GetPath = channel.unary_unary(
            "/optical.OpticalService/GetPath",
            request_serializer=optical__pb2.GetPathRequest.SerializeToString,
            response_deserializer=optical__pb2.OpticalPath.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/optical.OpticalService/Health",
            request_serializer=optical__pb2.HealthRequest.SerializeToString,
            response_deserializer=optical__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class OpticalServiceServicer:
    """OpticalService handles optical path computation and signal budget calculations"""

    def RecomputePaths(self, request, context):
        """Recompute optical paths for affected ONTs after topology changes
        This is the critical performance bottleneck (currently O(N²) in Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPath(self, request, context):
        """Get optical path details for a single ONT (debugging/UI)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health check endpoint"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OpticalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RecomputePaths": grpc.unary_unary_rpc_method_handler(
            servicer.RecomputePaths,
            request_deserializer=optical__pb2.RecomputeRequest.FromString,
            response_serializer=optical__pb2.RecomputeResponse.SerializeToString,
        ),
        "GetPath": grpc.unary_unary_rpc_method_handler(
            servicer.GetPath,
            request_deserializer=optical__pb2.GetPathRequest.FromString,
            response_serializer=optical__pb2.OpticalPath.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=optical__pb2.HealthRequest.FromString,
            response_serializer=optical__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "optical.OpticalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("optical.OpticalService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class OpticalService:
    """OpticalService handles optical path computation and signal budget calculations"""

    @staticmethod
    def RecomputePaths(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/optical.OpticalService/RecomputePaths",
            optical__pb2.RecomputeRequest.SerializeToString,
            optical__pb2.RecomputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/optical.OpticalService/GetPath",
            optical__pb2.GetPathRequest.SerializeToString,
            optical__pb2.OpticalPath.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/optical.OpticalService/Health",
            optical__pb2.HealthRequest.SerializeToString,
            optical__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
