// batch.proto - Batch Operations Service
// Week 3 Day 13: Protobuf definitions for bulk link/device operations
// Target: 262× speedup (64 links: 37 min → 8s)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: batch.proto

package batch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BatchService_BatchCreateLinks_FullMethodName = "/batch.BatchService/BatchCreateLinks"
	BatchService_BatchDeleteLinks_FullMethodName = "/batch.BatchService/BatchDeleteLinks"
	BatchService_HealthCheck_FullMethodName      = "/batch.BatchService/HealthCheck"
)

// BatchServiceClient is the client API for BatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BatchService handles bulk operations for links and devices
// All operations use single transactions for atomicity
type BatchServiceClient interface {
	// BatchCreateLinks creates multiple links in a single transaction
	// Target: 64 links in <10s (vs 37 min Python sequential)
	BatchCreateLinks(ctx context.Context, in *BatchCreateLinksRequest, opts ...grpc.CallOption) (*BatchCreateLinksResponse, error)
	// BatchDeleteLinks deletes multiple links in a single transaction
	// Target: 64 links in <5s (vs 15-20 min Python sequential)
	BatchDeleteLinks(ctx context.Context, in *BatchDeleteLinksRequest, opts ...grpc.CallOption) (*BatchDeleteLinksResponse, error)
	// HealthCheck verifies service is operational
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type batchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchServiceClient(cc grpc.ClientConnInterface) BatchServiceClient {
	return &batchServiceClient{cc}
}

func (c *batchServiceClient) BatchCreateLinks(ctx context.Context, in *BatchCreateLinksRequest, opts ...grpc.CallOption) (*BatchCreateLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateLinksResponse)
	err := c.cc.Invoke(ctx, BatchService_BatchCreateLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) BatchDeleteLinks(ctx context.Context, in *BatchDeleteLinksRequest, opts ...grpc.CallOption) (*BatchDeleteLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteLinksResponse)
	err := c.cc.Invoke(ctx, BatchService_BatchDeleteLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, BatchService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchServiceServer is the server API for BatchService service.
// All implementations must embed UnimplementedBatchServiceServer
// for forward compatibility.
//
// BatchService handles bulk operations for links and devices
// All operations use single transactions for atomicity
type BatchServiceServer interface {
	// BatchCreateLinks creates multiple links in a single transaction
	// Target: 64 links in <10s (vs 37 min Python sequential)
	BatchCreateLinks(context.Context, *BatchCreateLinksRequest) (*BatchCreateLinksResponse, error)
	// BatchDeleteLinks deletes multiple links in a single transaction
	// Target: 64 links in <5s (vs 15-20 min Python sequential)
	BatchDeleteLinks(context.Context, *BatchDeleteLinksRequest) (*BatchDeleteLinksResponse, error)
	// HealthCheck verifies service is operational
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedBatchServiceServer()
}

// UnimplementedBatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchServiceServer struct{}

func (UnimplementedBatchServiceServer) BatchCreateLinks(context.Context, *BatchCreateLinksRequest) (*BatchCreateLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateLinks not implemented")
}
func (UnimplementedBatchServiceServer) BatchDeleteLinks(context.Context, *BatchDeleteLinksRequest) (*BatchDeleteLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteLinks not implemented")
}
func (UnimplementedBatchServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBatchServiceServer) mustEmbedUnimplementedBatchServiceServer() {}
func (UnimplementedBatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeBatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchServiceServer will
// result in compilation errors.
type UnsafeBatchServiceServer interface {
	mustEmbedUnimplementedBatchServiceServer()
}

func RegisterBatchServiceServer(s grpc.ServiceRegistrar, srv BatchServiceServer) {
	// If the following call pancis, it indicates UnimplementedBatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchService_ServiceDesc, srv)
}

func _BatchService_BatchCreateLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).BatchCreateLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_BatchCreateLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).BatchCreateLinks(ctx, req.(*BatchCreateLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_BatchDeleteLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).BatchDeleteLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_BatchDeleteLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).BatchDeleteLinks(ctx, req.(*BatchDeleteLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchService_ServiceDesc is the grpc.ServiceDesc for BatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "batch.BatchService",
	HandlerType: (*BatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchCreateLinks",
			Handler:    _BatchService_BatchCreateLinks_Handler,
		},
		{
			MethodName: "BatchDeleteLinks",
			Handler:    _BatchService_BatchDeleteLinks_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _BatchService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "batch.proto",
}
