# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import port_summary_pb2 as port__summary__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in port_summary_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PortSummaryServiceStub(object):
    """Port Summary Service - Fast interface summary for devices
    Replaces slow Python bulk queries with in-memory Go service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPortSummary = channel.unary_unary(
            "/port_summary.PortSummaryService/GetPortSummary",
            request_serializer=port__summary__pb2.DeviceRequest.SerializeToString,
            response_deserializer=port__summary__pb2.PortSummaryResponse.FromString,
            _registered_method=True,
        )
        self.GetBulkPortSummary = channel.unary_unary(
            "/port_summary.PortSummaryService/GetBulkPortSummary",
            request_serializer=port__summary__pb2.BulkDeviceRequest.SerializeToString,
            response_deserializer=port__summary__pb2.BulkPortSummaryResponse.FromString,
            _registered_method=True,
        )
        self.InvalidateCache = channel.unary_unary(
            "/port_summary.PortSummaryService/InvalidateCache",
            request_serializer=port__summary__pb2.InvalidateCacheRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/port_summary.PortSummaryService/HealthCheck",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=port__summary__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class PortSummaryServiceServicer(object):
    """Port Summary Service - Fast interface summary for devices
    Replaces slow Python bulk queries with in-memory Go service
    """

    def GetPortSummary(self, request, context):
        """Get port summary for a single device"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBulkPortSummary(self, request, context):
        """Get port summaries for multiple devices (bulk)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InvalidateCache(self, request, context):
        """Invalidate cache for a device (triggered by events)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check endpoint"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PortSummaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPortSummary": grpc.unary_unary_rpc_method_handler(
            servicer.GetPortSummary,
            request_deserializer=port__summary__pb2.DeviceRequest.FromString,
            response_serializer=port__summary__pb2.PortSummaryResponse.SerializeToString,
        ),
        "GetBulkPortSummary": grpc.unary_unary_rpc_method_handler(
            servicer.GetBulkPortSummary,
            request_deserializer=port__summary__pb2.BulkDeviceRequest.FromString,
            response_serializer=port__summary__pb2.BulkPortSummaryResponse.SerializeToString,
        ),
        "InvalidateCache": grpc.unary_unary_rpc_method_handler(
            servicer.InvalidateCache,
            request_deserializer=port__summary__pb2.InvalidateCacheRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=port__summary__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "port_summary.PortSummaryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("port_summary.PortSummaryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PortSummaryService(object):
    """Port Summary Service - Fast interface summary for devices
    Replaces slow Python bulk queries with in-memory Go service
    """

    @staticmethod
    def GetPortSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/port_summary.PortSummaryService/GetPortSummary",
            port__summary__pb2.DeviceRequest.SerializeToString,
            port__summary__pb2.PortSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBulkPortSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/port_summary.PortSummaryService/GetBulkPortSummary",
            port__summary__pb2.BulkDeviceRequest.SerializeToString,
            port__summary__pb2.BulkPortSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InvalidateCache(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/port_summary.PortSummaryService/InvalidateCache",
            port__summary__pb2.InvalidateCacheRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/port_summary.PortSummaryService/HealthCheck",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            port__summary__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
