# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: port_summary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'port_summary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12port_summary.proto\x12\x0cport_summary\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\rDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\'\n\x11\x42ulkDeviceRequest\x12\x12\n\ndevice_ids\x18\x01 \x03(\t\"\x90\x01\n\x10InterfaceSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tport_role\x18\x03 \x01(\t\x12\x18\n\x10\x65\x66\x66\x65\x63tive_status\x18\x04 \x01(\t\x12\x11\n\toccupancy\x18\x05 \x01(\x05\x12\x15\n\x08\x63\x61pacity\x18\x06 \x01(\x05H\x00\x88\x01\x01\x42\x0b\n\t_capacity\"I\n\x13PortSummaryResponse\x12\x32\n\ninterfaces\x18\x01 \x03(\x0b\x32\x1e.port_summary.InterfaceSummary\"\xb7\x01\n\x17\x42ulkPortSummaryResponse\x12G\n\tsummaries\x18\x01 \x03(\x0b\x32\x34.port_summary.BulkPortSummaryResponse.SummariesEntry\x1aS\n\x0eSummariesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.port_summary.PortSummaryResponse:\x02\x38\x01\"+\n\x16InvalidateCacheRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x80\x01\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x16\n\x0e\x63\x61\x63hed_devices\x18\x02 \x01(\x05\x12\x19\n\x11\x63\x61\x63hed_interfaces\x18\x03 \x01(\x05\x12\x14\n\x0c\x63\x61\x63hed_links\x18\x04 \x01(\x05\x12\x0f\n\x07version\x18\x05 \x01(\t2\xdf\x02\n\x12PortSummaryService\x12P\n\x0eGetPortSummary\x12\x1b.port_summary.DeviceRequest\x1a!.port_summary.PortSummaryResponse\x12\\\n\x12GetBulkPortSummary\x12\x1f.port_summary.BulkDeviceRequest\x1a%.port_summary.BulkPortSummaryResponse\x12O\n\x0fInvalidateCache\x12$.port_summary.InvalidateCacheRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a!.port_summary.HealthCheckResponseB/Z-github.com/yourusername/unoc/gen/port_summaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'port_summary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/yourusername/unoc/gen/port_summary'
  _globals['_BULKPORTSUMMARYRESPONSE_SUMMARIESENTRY']._loaded_options = None
  _globals['_BULKPORTSUMMARYRESPONSE_SUMMARIESENTRY']._serialized_options = b'8\001'
  _globals['_DEVICEREQUEST']._serialized_start=65
  _globals['_DEVICEREQUEST']._serialized_end=99
  _globals['_BULKDEVICEREQUEST']._serialized_start=101
  _globals['_BULKDEVICEREQUEST']._serialized_end=140
  _globals['_INTERFACESUMMARY']._serialized_start=143
  _globals['_INTERFACESUMMARY']._serialized_end=287
  _globals['_PORTSUMMARYRESPONSE']._serialized_start=289
  _globals['_PORTSUMMARYRESPONSE']._serialized_end=362
  _globals['_BULKPORTSUMMARYRESPONSE']._serialized_start=365
  _globals['_BULKPORTSUMMARYRESPONSE']._serialized_end=548
  _globals['_BULKPORTSUMMARYRESPONSE_SUMMARIESENTRY']._serialized_start=465
  _globals['_BULKPORTSUMMARYRESPONSE_SUMMARIESENTRY']._serialized_end=548
  _globals['_INVALIDATECACHEREQUEST']._serialized_start=550
  _globals['_INVALIDATECACHEREQUEST']._serialized_end=593
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=596
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=724
  _globals['_PORTSUMMARYSERVICE']._serialized_start=727
  _globals['_PORTSUMMARYSERVICE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
