// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/status.proto

package status

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatusService_PropagateStatus_FullMethodName  = "/status.StatusService/PropagateStatus"
	StatusService_GetDependencies_FullMethodName  = "/status.StatusService/GetDependencies"
	StatusService_BulkUpdateStatus_FullMethodName = "/status.StatusService/BulkUpdateStatus"
	StatusService_Health_FullMethodName           = "/status.StatusService/Health"
)

// StatusServiceClient is the client API for StatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StatusService handles status dependency resolution and propagation
// Goal: Propagate status changes through dependency tree efficiently
type StatusServiceClient interface {
	// Propagate status changes through dependency tree
	PropagateStatus(ctx context.Context, in *PropagateRequest, opts ...grpc.CallOption) (*PropagateResponse, error)
	// Get dependency tree for a device (upstream dependencies)
	GetDependencies(ctx context.Context, in *GetDepsRequest, opts ...grpc.CallOption) (*DependencyTree, error)
	// Bulk status update (set status for multiple devices)
	BulkUpdateStatus(ctx context.Context, in *BulkStatusRequest, opts ...grpc.CallOption) (*BulkStatusResponse, error)
	// Health check endpoint
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type statusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusServiceClient(cc grpc.ClientConnInterface) StatusServiceClient {
	return &statusServiceClient{cc}
}

func (c *statusServiceClient) PropagateStatus(ctx context.Context, in *PropagateRequest, opts ...grpc.CallOption) (*PropagateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropagateResponse)
	err := c.cc.Invoke(ctx, StatusService_PropagateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusServiceClient) GetDependencies(ctx context.Context, in *GetDepsRequest, opts ...grpc.CallOption) (*DependencyTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DependencyTree)
	err := c.cc.Invoke(ctx, StatusService_GetDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusServiceClient) BulkUpdateStatus(ctx context.Context, in *BulkStatusRequest, opts ...grpc.CallOption) (*BulkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkStatusResponse)
	err := c.cc.Invoke(ctx, StatusService_BulkUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StatusService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServiceServer is the server API for StatusService service.
// All implementations must embed UnimplementedStatusServiceServer
// for forward compatibility.
//
// StatusService handles status dependency resolution and propagation
// Goal: Propagate status changes through dependency tree efficiently
type StatusServiceServer interface {
	// Propagate status changes through dependency tree
	PropagateStatus(context.Context, *PropagateRequest) (*PropagateResponse, error)
	// Get dependency tree for a device (upstream dependencies)
	GetDependencies(context.Context, *GetDepsRequest) (*DependencyTree, error)
	// Bulk status update (set status for multiple devices)
	BulkUpdateStatus(context.Context, *BulkStatusRequest) (*BulkStatusResponse, error)
	// Health check endpoint
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStatusServiceServer()
}

// UnimplementedStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusServiceServer struct{}

func (UnimplementedStatusServiceServer) PropagateStatus(context.Context, *PropagateRequest) (*PropagateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PropagateStatus not implemented")
}
func (UnimplementedStatusServiceServer) GetDependencies(context.Context, *GetDepsRequest) (*DependencyTree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedStatusServiceServer) BulkUpdateStatus(context.Context, *BulkStatusRequest) (*BulkStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUpdateStatus not implemented")
}
func (UnimplementedStatusServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStatusServiceServer) mustEmbedUnimplementedStatusServiceServer() {}
func (UnimplementedStatusServiceServer) testEmbeddedByValue()                       {}

// UnsafeStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusServiceServer will
// result in compilation errors.
type UnsafeStatusServiceServer interface {
	mustEmbedUnimplementedStatusServiceServer()
}

func RegisterStatusServiceServer(s grpc.ServiceRegistrar, srv StatusServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatusService_ServiceDesc, srv)
}

func _StatusService_PropagateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropagateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).PropagateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusService_PropagateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).PropagateStatus(ctx, req.(*PropagateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusService_GetDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).GetDependencies(ctx, req.(*GetDepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusService_BulkUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).BulkUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusService_BulkUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).BulkUpdateStatus(ctx, req.(*BulkStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusService_ServiceDesc is the grpc.ServiceDesc for StatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "status.StatusService",
	HandlerType: (*StatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PropagateStatus",
			Handler:    _StatusService_PropagateStatus_Handler,
		},
		{
			MethodName: "GetDependencies",
			Handler:    _StatusService_GetDependencies_Handler,
		},
		{
			MethodName: "BulkUpdateStatus",
			Handler:    _StatusService_BulkUpdateStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _StatusService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/status.proto",
}
