# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import status_pb2 as status__pb2

GRPC_GENERATED_VERSION = "1.66.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in status_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class StatusServiceStub:
    """StatusService handles status dependency resolution and propagation
    Goal: Propagate status changes through dependency tree efficiently
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PropagateStatus = channel.unary_unary(
            "/status.StatusService/PropagateStatus",
            request_serializer=status__pb2.PropagateRequest.SerializeToString,
            response_deserializer=status__pb2.PropagateResponse.FromString,
            _registered_method=True,
        )
        self.GetDependencies = channel.unary_unary(
            "/status.StatusService/GetDependencies",
            request_serializer=status__pb2.GetDepsRequest.SerializeToString,
            response_deserializer=status__pb2.DependencyTree.FromString,
            _registered_method=True,
        )
        self.BulkUpdateStatus = channel.unary_unary(
            "/status.StatusService/BulkUpdateStatus",
            request_serializer=status__pb2.BulkStatusRequest.SerializeToString,
            response_deserializer=status__pb2.BulkStatusResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/status.StatusService/Health",
            request_serializer=status__pb2.HealthRequest.SerializeToString,
            response_deserializer=status__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class StatusServiceServicer:
    """StatusService handles status dependency resolution and propagation
    Goal: Propagate status changes through dependency tree efficiently
    """

    def PropagateStatus(self, request, context):
        """Propagate status changes through dependency tree"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDependencies(self, request, context):
        """Get dependency tree for a device (upstream dependencies)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BulkUpdateStatus(self, request, context):
        """Bulk status update (set status for multiple devices)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health check endpoint"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PropagateStatus": grpc.unary_unary_rpc_method_handler(
            servicer.PropagateStatus,
            request_deserializer=status__pb2.PropagateRequest.FromString,
            response_serializer=status__pb2.PropagateResponse.SerializeToString,
        ),
        "GetDependencies": grpc.unary_unary_rpc_method_handler(
            servicer.GetDependencies,
            request_deserializer=status__pb2.GetDepsRequest.FromString,
            response_serializer=status__pb2.DependencyTree.SerializeToString,
        ),
        "BulkUpdateStatus": grpc.unary_unary_rpc_method_handler(
            servicer.BulkUpdateStatus,
            request_deserializer=status__pb2.BulkStatusRequest.FromString,
            response_serializer=status__pb2.BulkStatusResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=status__pb2.HealthRequest.FromString,
            response_serializer=status__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "status.StatusService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("status.StatusService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class StatusService:
    """StatusService handles status dependency resolution and propagation
    Goal: Propagate status changes through dependency tree efficiently
    """

    @staticmethod
    def PropagateStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/status.StatusService/PropagateStatus",
            status__pb2.PropagateRequest.SerializeToString,
            status__pb2.PropagateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDependencies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/status.StatusService/GetDependencies",
            status__pb2.GetDepsRequest.SerializeToString,
            status__pb2.DependencyTree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BulkUpdateStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/status.StatusService/BulkUpdateStatus",
            status__pb2.BulkStatusRequest.SerializeToString,
            status__pb2.BulkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/status.StatusService/Health",
            status__pb2.HealthRequest.SerializeToString,
            status__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
