"""Central constants package.

Exports provisioning & link classification tables used across services.
"""

from .link_types import LINK_TYPE_RULES, ONT_CLASS, PASSIVE_INLINE, ROUTER_CLASS
from .optical import FIBER_TYPE_KEYS, FIBER_TYPES
from .provisioning import (
    DEVICE_PARENT_POOL_MAP,
    ENABLE_RING_PROTECTION,
    POOL_DEFS,
    POOL_KEY_MAP,
    PROVISION_MATRIX,
    PROVISIONABLE_TYPES,
    RING_PROTECTION_DEBOUNCE_MS,
    RING_PROTECTION_DETERMINISM,
    RING_PROTECTION_IGNORE_PASSIVE_NODES,
    RING_PROTECTION_MAX_CYCLE_LENGTH,
    RING_PROTECTION_MAX_RINGS_TRACKED,
    RING_PROTECTION_OVERLAP_STRATEGY,
    RING_PROTECTION_RECOVERY_DELAY_MS,
)

__all__ = [
    "PROVISIONABLE_TYPES",
    "DEVICE_PARENT_POOL_MAP",
    "POOL_KEY_MAP",
    "POOL_DEFS",
    "PROVISION_MATRIX",
    "ENABLE_RING_PROTECTION",
    "RING_PROTECTION_DETERMINISM",
    "RING_PROTECTION_DEBOUNCE_MS",
    "RING_PROTECTION_RECOVERY_DELAY_MS",
    "RING_PROTECTION_MAX_CYCLE_LENGTH",
    "RING_PROTECTION_MAX_RINGS_TRACKED",
    "RING_PROTECTION_OVERLAP_STRATEGY",
    "RING_PROTECTION_IGNORE_PASSIVE_NODES",
    "LINK_TYPE_RULES",
    "ROUTER_CLASS",
    "PASSIVE_INLINE",
    "ONT_CLASS",
    "FIBER_TYPE_KEYS",
    "FIBER_TYPES",
]
